name: codeguru
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  # for writing security events.
  security-events: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::373508513302:role/CodeGuruSecurityGitHubAccessRole
          aws-region: eu-west-1
          role-session-name: GitHubActionScript

      - name: CodeGuru Security
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: src
          aws_region: eu-west-1
          fail_on_severity: High

      - name: Upload result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codeguru-security-results.sarif.json
